
# Syntax highlighting
markdown:            kramdown
highlighter:         pygments

# Permalinks
permalink:           /:title
# relative_permalinks: true

# Setup
timezone:            Europe/Kiev # eg. Asia/Kathmandu
locale:              en_us # eg. en_us
name:				         'Web Scraping'
title:               Scraping
tagline:             'scraping, parsing, python, ruby'
description:         'description'
url:                 'http://max-si-m.github.io'
rss:                 'feed.xml'
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              scrapingblog # get it on https://disqus.com/admin/

author:
  name:           	 'Maxim Dzhuliy'
  url:            	 'http://max-si-m.github.io/'
  facebook:          max.djuliy
  twitter:           max_si_m
  github:            max-si-m
  google_plus:       username
  linkedin:          maximdjuliy
  dribbble:          username
  pinterest:         username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 4000

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
